[tool.poetry]
name = "blog_fastapi"
version = "0.1.0"
description = "API banc√°ria simples com FastAPI e SQLModel"
authors = ["Fabiano <seu-email@example.com>"]

[tool.poetry.dependencies]
python = "^3.13"
fastapi = "^0.111.1"
uvicorn = "^0.23.0"
sqlmodel = "^0.0.8"

[tool.poetry.dev-dependencies]
pytest = "^7.4.2"

[build-system]
requires = ["poetry-core>=1.6.0"]
build-backend = "poetry.core.masonry.api"
