services:
  - type: web
    name: transactions-api
    runtime: python
    plan: free
    buildCommand: |
      pip install poetry
      poetry config virtualenvs.create false
      poetry install --no-interaction --no-ansi
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: blog_fastapi
          property: connectionString

databases:
  - name: blog_fastapi
    plan: basic-1gb
    postgresMajorVersion: "18"