services:
  - type: web
    name: transactions-api
    env: python
    plan: free
    buildCommand: |
      pip install poetry
      poetry config virtualenvs.create false
      poetry install --no-interaction --no-ansi
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: blog_fastapi
          property: connectionString
