services:
  - type: web
    name: transactions-api
    runtime: python
    plan: free
    buildCommand: |
      pip install poetry
      poetry config virtualenvs.create false
      poetry install --no-interaction --no-ansi
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: blog_fastapi   # isso precisa bater com o nome do banco no painel
          property: connectionString

databases:
  - name: blog_fastapi     # esse nome tamb√©m deve bater
    plan: basic-1gb
    postgresMajorVersion: "18"
